\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory

# Load your packages

# Set your ggplot theme

# Load your datasets

```


# Rationale and Research Questions

  As disturbance regimes across the United States change, we thought it was important to assess trends, differences, and changes in specific fire regimes. We decided to focus our study on the three states with the most large fire occurrences because...



**Research Questions:**

**Question 1:** Do the mean sizes of large wildfires in California differ between 1988 and 2000? 

**Question 2:** Is there a difference between large wildfire sizes in the 3 states with the most large wildfire occurrences? (California, Idaho, and Nevada) 

**Question 3:** Is there a trend in large fire occurrences in California from 1984 to 2007? - What is the trend in wildfire, prescribed fires and wildland fire use over the same years? 


\newpage

# Dataset Information

  The dataset we used in our analysis is titled "Monitoring Trends in Burn Severity Burned Area Boundaries." The United States Forest Service published this data and it was first published on May 4th, 2017, but has since been modified on August 8th, 2022. This data was collected using the Landsat Thematic Mapper and USFS data from each fire incident. This data is a feature layer, so it is geospatial data. This dataset was a part of a project called "Monitoring Trends in Burn Severity (MTBS)" that "assesses the frequency, extent, and magnitude (size and severity) of all large wildland fires." The term large wildland fire includes wildfire, wildland use fires (fires set as a means of suppression), and prescribed burns. The size of a large wildland fire varies; in the western US, a large wildland fire is any fire larger than 1,000 acres; in the eastern US, a large wildland fire is any fire larger than 500 acres. This data covers the entire United States and includes Puerto Rico. 

  To wrangle the data, we started by reading the csv file into our rmarkdown document. We then were able to use the pipe function (%>%) with the select() function for the data set to import only the columns we needed for our analysis. These columns included the fire size (acres), fire id, state, fire name, year, start month, start day, fire type, latitude, and longitude. After we had the columns we needed, the next step was to use the substr() function on the fire id column because all we needed from this column was the state abbreviation. Using substr(), we were able to include only the first two characters in the ID. Once we only had the state abbreviations in this column, we renamed the column using the pipe function (%>%) and the rename() function to rename it to STATE. The final step was to use write.csv() to save the processed dataset to our processed folder. 
  
|  Variable   |   Units   |Data Range and Description                    | Data Type       |
|-------------|-----------|----------------------------------------------|-----------------|
| Fire Size   | Acres     | 500 - 593,364                                | Quantitative    |
| State       |           | U.S.A. Including Puerto Rico.                | Qualitative     |
| Fire Name   |           | On Scene Fire Name                           | Qualitative     | 
| Year        | Year #    | Fire state year                              | Qualitative     | 
| Start Month | Month #   | Fire start month number                      | Qualitative     | 
| Start Day   | Day #     | Fire start day number                        | Qualitative     | 
| Fire Type   |           | Wildfire, Wildland Use Fire, Prescribed Burn | Qualitative     | 
| Latitude    | Degrees N | 17.957 - 69.465                              | Quantitative    | 
| Longitude   | Degrees W | -66.129 - -165.881                           | Quantitative    | 


\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 

## Question 3: 


\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
