---
title: "Two-Sample T Test"
author: "Li Jia Go"
date: "2022-11-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
install.packages('formatR')
library(formatR)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
```

## Research Question

Do the mean sizes of large wildfires in California differ between 1988 and 2000?

```{r, data exploration}
library(tidyverse)
library(dplyr)
library(ggplot2)

USFireData <- read.csv("./Data/Processed/US_FireData_Processed.csv", 
                stringsAsFactors = TRUE) 

#filtering dataset for wildfires in California in years 1988 and 2000
California.Wildfires <- USFireData %>%
  filter(STATE %in% "CA") %>%
  filter(FIRE_TYPE %in% "Wildfire") %>%
  filter(YEAR %in% c("1988", "2000"))

#data exploration 
ggplot(California.Wildfires, aes(x = ACRES, color =as.factor(YEAR))) +
  geom_freqpoly() +
  labs(x='Acreage of fires', y='Count', color='Year', 
       title="Histogram of wildfires in 1988 & 2000, California")  
  

```
### Two-sample t-test

The two-sample *t* test is used to test the hypothesis that the mean of two samples is equivalent. Unlike the one-sample tests, a two-sample test requires a second assumption that the variance of the two groups is equivalent. 
H0: means are equal
h1: means are not equal. 


```{r, two-sample t test}

#running two-sample t test
twosamp.ttest <- t.test(California.Wildfires$ACRES ~ California.Wildfires$YEAR)
twosamp.ttest
#p= 0.3754>0.05, we accept the null hypothesis that means are statistically equal for both years. 


```